name: Publish Docker Image on main

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker Container
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push web
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/girder.Dockerfile
          tags: ghcr.io/umd-annotation/umd-annotation-tool/umd-annotation-web:latest
          push: true
      -
        name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/girder_worker.Dockerfile
          tags: ghcr.io/umd-annotation/umd-annotation-tool/umd-annotation-w:latest
          push: true